// swift-tools-version: 5.9
// VoxylioKit — the pure engine pieces the native macOS app needs
// (sentence grouping, speech pacing, glossary protection), ported from
// packages/core. Parity with the JS reference implementation is enforced
// by the shared vectors in Tests/VoxylioKitTests/Fixtures/vectors.json
// (generated by packages/core/scripts/export-vectors.mjs).
import PackageDescription

let package = Package(
    name: "VoxylioKit",
    platforms: [.macOS(.v13)],
    products: [
        .library(name: "VoxylioKit", targets: ["VoxylioKit"])
    ],
    targets: [
        .target(name: "VoxylioKit"),
        .testTarget(
            name: "VoxylioKitTests",
            dependencies: ["VoxylioKit"],
            resources: [.copy("Fixtures")]
        ),
    ]
)
