// Parity tests: VoxylioKit must produce EXACTLY what the JS reference
// engine produces. Fixtures/vectors.json is generated by
// packages/core/scripts/export-vectors.mjs — regenerate there, never
// hand-edit here.

import XCTest
@testable import VoxylioKit

// MARK: - Vector schema

private struct Vectors: Decodable {
    let textHash: [TextHashCase]
    let wordOverlap: [WordOverlapCase]
    let mergeRollup: [MergeRollupCase]
    let buildGroups: [BuildGroupsCase]
    let pacing: [PacingCase]
    let glossary: [GlossaryCase]
    let cleanCaption: [CleanCaptionCase]
    let endsSentence: [EndsSentenceCase]
}

private struct TextHashCase: Decodable {
    let input: String
    let expected: String
}

private struct WordOverlapCase: Decodable {
    let a: String
    let b: String
    let minWords: Int
    let expected: Int
}

private struct LastCue: Decodable {
    let text: String
    let end: Double
}

private struct MergeExpected: Decodable {
    let text: String
    let end: Double
    let grew: Bool
}

private struct MergeRollupCase: Decodable {
    let last: LastCue?
    let start: Double
    let end: Double
    let text: String
    let expected: MergeExpected?
}

private struct VectorCue: Decodable {
    let start: Double
    let end: Double
    let text: String
}

private struct VectorGroup: Decodable {
    let start: Double
    let end: Double
    let text: String
    let id: String
    let version: String
    let final: Bool
    let key: String
}

private struct BuildGroupsCase: Decodable {
    let name: String
    let cues: [VectorCue]
    let expected: [VectorGroup]
}

private struct PacingCase: Decodable {
    let text: String
    let cueDur: Double
    let baseRate: Double
    let playbackRate: Double
    let expected: Double
}

private struct GlossaryCase: Decodable {
    let input: String
    let protectedText: String
    let found: [String]
    let translated: String
    let restored: String
    let ok: Bool
}

private struct CleanCaptionCase: Decodable {
    let input: String
    let expected: String
}

private struct EndsSentenceCase: Decodable {
    let input: String
    let expected: Bool
}

// MARK: - Tests

final class VectorTests: XCTestCase {
    private static let vectors: Vectors = {
        guard
            let url = Bundle.module.url(
                forResource: "vectors", withExtension: "json", subdirectory: "Fixtures")
        else {
            fatalError("Fixtures/vectors.json missing — run packages/core/scripts/export-vectors.mjs")
        }
        // swiftlint:disable:next force_try
        let data = try! Data(contentsOf: url)
        // swiftlint:disable:next force_try
        return try! JSONDecoder().decode(Vectors.self, from: data)
    }()

    func testTextHash() {
        for c in Self.vectors.textHash {
            XCTAssertEqual(textHash(c.input), c.expected, "textHash(\(c.input))")
        }
    }

    func testWordOverlap() {
        for c in Self.vectors.wordOverlap {
            XCTAssertEqual(
                wordOverlap(c.a, c.b, minWords: c.minWords), c.expected,
                "wordOverlap(\(c.a) | \(c.b))")
        }
    }

    func testMergeRollup() {
        for c in Self.vectors.mergeRollup {
            let res = mergeRollup(
                lastText: c.last?.text, lastEnd: c.last?.end ?? 0,
                start: c.start, end: c.end, text: c.text)
            if let expected = c.expected {
                XCTAssertNotNil(res, "expected a merge for \(c.text)")
                XCTAssertEqual(res?.text, expected.text)
                XCTAssertEqual(res?.end ?? -1, expected.end, accuracy: 1e-9)
                XCTAssertEqual(res?.grew, expected.grew)
            } else {
                XCTAssertNil(res, "expected NO merge for \(c.text)")
            }
        }
    }

    func testBuildGroups() {
        for c in Self.vectors.buildGroups {
            let groups = buildGroups(c.cues.map { Cue(start: $0.start, end: $0.end, text: $0.text) })
            XCTAssertEqual(groups.count, c.expected.count, c.name)
            for (g, e) in zip(groups, c.expected) {
                XCTAssertEqual(g.id, e.id, c.name)
                XCTAssertEqual(g.version, e.version, c.name)
                XCTAssertEqual(g.text, e.text, c.name)
                XCTAssertEqual(g.final, e.final, c.name)
                XCTAssertEqual(g.key, e.key, c.name)
                XCTAssertEqual(g.start, e.start, accuracy: 1e-9, c.name)
                XCTAssertEqual(g.end, e.end, accuracy: 1e-9, c.name)
            }
        }
    }

    func testPacing() {
        for c in Self.vectors.pacing {
            let rate = computeUtteranceRate(
                text: c.text, cueDur: c.cueDur, baseRate: c.baseRate,
                playbackRate: c.playbackRate)
            XCTAssertEqual(rate, c.expected, accuracy: 1e-12, c.text)
        }
    }

    func testGlossary() {
        for c in Self.vectors.glossary {
            let (protectedText, found) = protectTerms(c.input)
            XCTAssertEqual(protectedText, c.protectedText, c.input)
            XCTAssertEqual(found, c.found, c.input)
            let (restored, ok) = restoreTerms(c.translated, found: found)
            XCTAssertEqual(restored, c.restored, c.input)
            XCTAssertEqual(ok, c.ok, c.input)
        }
    }

    func testCleanCaption() {
        for c in Self.vectors.cleanCaption {
            XCTAssertEqual(cleanCaption(c.input), c.expected, c.input)
        }
    }

    func testEndsSentence() {
        for c in Self.vectors.endsSentence {
            XCTAssertEqual(endsSentence(c.input), c.expected, c.input)
        }
    }
}
